name: pollenexport

on:
  push:
    branches: ['pollen']

jobs:
  pollen:
    name: "Pollen documentation build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pollen
          path: static/data
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: actions/checkout@v2
        with:
          repository: lorenzoh/pollenjl-frontend
          path: '.'
          ref: main
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy changes
        run: |
          cp -r build/** gh-pages
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .
          git commit -m "Deploy documentation (Pollen.jl)"
          git push

