name: pollenexport

on:
  push:
    branches: ['pollen']

jobs:
  pollen:
    name: "Pollen documentation build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pollen
          path: data
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "pages"
      - uses: actions/checkout@v2
        with:
          repository: lorenzoh/pollenjl-frontend
          path: frontend
          ref: main
      - name: Move Pollen data to static folder
        run: |
          ls
          mv data/ frontend/static
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Deploy changes
        run: |
          ls -lt
          cp -r frontend/build/** pages
          cd pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .
          git commit -m "Deploy documentation (Pollen.jl)"
          git push

